version: '3'
services:
  app:
    build:
      context: ./app
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data  # Map the 'data' directory to '/app/data' inside the container

  # I'm having some issue in local laptop with Faced some challenges with elasticsearch, so I commented the code
  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
  #   container_name: elasticsearch
  #   environment:
  #     - "discovery.type=single-node"
  #   ports:
  #     - "9200:9200"
  #     - "9300:9300"
  #   volumes:
  #     - ./data:/usr/share/elasticsearch/data
